spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: password
  jpa:
    hibernate-dll-auto: update
    generate-ddl: true
    show-sql: true