spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: letmein
  jpa:
    hibernate-dll-auto: update
    generate-ddl: true
    show-sql: true
